[build-system]
requires = ["maturin>=1.7,<2.0"]
build-backend = "maturin"

[project]
name = "proteus"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.1.0",
    "scikit-learn>=1.5.0",
    "torch>=2.5.0",
]

[tool.maturin]
features = ["pyo3/extension-module"]